useless = {
    'Power': [
        "You can sneeze confetti, but it gives you a headache every time",
        "You can communicate with ants, but they never have anything interesting to say",
        "You can predict the exact time that a bird will poop on your head, but you can't avoid it",
        "You can turn invisible, but only for one second at a time and it takes an hour to recharge",
        "You can teleport, but it only works when you're within a foot of your current location",
        "You can speak every language in the world, but you can only do so while standing on one foot",
        "You can fly, but only at a maximum height of three feet off the ground",
        "You can breathe underwater, but only for five seconds at a time",
        "You can talk to plants, but they're all really boring conversationalists",
        "You can walk through walls, but only if the wall is already open",
        "You can make your hair grow at an accelerated rate, but only on your toes",
        "You have perfect pitch, but only for the sound of fingernails on a chalkboard",
        "You can freeze time, but you're also frozen during that time",
        "You can hear thoughts, but only the thoughts of inanimate objects",
        "You can make any object within five feet of you levitate, but you can't control where it goes",
        "You can create fire from your fingertips, but it's always at a temperature too low to be useful",
        "You can turn invisible, but only while screaming at the top of your lungs",
        "You can summon any object, but it always appears in the most inconvenient location possible",
        "You can see into the future, but only by five seconds",
        "You can communicate with ghosts, but they only want to talk about their favorite TV shows",
        "Whenever a bird flies over your head, your shoes change color randomly",
        "Every time you take a step backwards, you lose one dollar from your bank account",
        "You can speak every language fluently, but only while standing on one foot",
        "Every time you sneeze, a random object within 10 feet of you disappears",
        "You can breathe underwater, but only in a bathtub",
        "Every time you snap your fingers, a mosquito appears and lands on your face",
        "You can turn invisible, but only for one second at a time and with a one-minute cooldown",
        "Every time you touch your nose, your clothes change into a clown outfit",
        "You can teleport anywhere you want, but every time you do, you have a 50% chance of ending up naked",
        "Every time you hear someone say your name, you have to do a cartwheel",
        "You can control the weather, but only on days when it's already sunny",
        "Every time you yawn, you have to tell a bad joke to the nearest person",
        "You can fly, but only at a maximum speed of 1 mile per hour",
        "Every time you try to take a picture of yourself, your phone explodes",
        "You can read minds, but only while doing a handstand",
        "Shouting a random animal name before sneezing makes the sneeze sound like that animal",
        "When you snap your fingers, a random person on the other side of the world gets a hiccups",
        "Every time you eat a piece of fruit, you gain the ability to speak a random language for 5 minutes",
        "Any time you walk through a door, you forget why you went through it",
        "Whenever you try to take a photo of something, it always comes out blurry",
        "You can predict the outcome of any coin toss, but only after it has already landed",
        "Whenever you read a book, you immediately forget the last chapter you read",
        "Your voice becomes inaudible to humans every time you try to sing",
        "You can make any plant grow to twice its size, but it always dies the next day",
        "Every time you brush your teeth, your hair grows one inch longer",
        "You can speak with animals, but they only ever want to talk about mundane topics",
        "Whenever you touch something blue, you get a mild electric shock",
        "You can make any object levitate, but only one centimeter off the ground",
        "Any time you use a public restroom, the toilet paper is always out",
        "You can teleport anywhere in the world, but it takes you 24 hours to recover from the nausea",
        "Every time you fart you become invisible",
        "After exactly 1000 failed attepts in a certain task, you get an unhuman boost that allows you to beat the current world record, by the smallest „in competition“ messurable unit.",
        "Every time you throw a chair at someone's head, you know the exact location of the nearest stick of butter.",
        "Whenever you stub your toe, you know the exact location of Queen Elizabeth for 12 seconds :",
        "Every time you blink, you lose the ability to see until you open your eyes again.",
        "For every occurrence in which thee pleasures thyself whilst in the process of interacting with an electronic visual interface, thy wordsmithing abilities is incrementally augmented a thousandfold.",
        "Everytime you get sad, drops of water excrete from your eyes.",
        "Everytime you don't have enough money to buy something, you can spawn Elon Musk to buy it for you, but he forgot his wallet.",
        "Every time you or someone near you says elephant, you summon an elephant but it has no legs",
        "Whenever wifi, bluetooth, or power goes out you're allowed to use an audio outputting device to play music, but you can only play payphone by maroon5 (and yes it can loop",
        "Ever time you sneeze you turn invisible for 2 seconds",
        "Whenever you pick up a phone it will return to full charges, but it doesn't work on your own phone",
        "Being able to set yourself on fire, but you're not resistant to fire, so the fire hurts when you do.",
        "When you sneeze, you have a 0.005% chance of causing a small explosion, you are harmed by it and everything else is fine",
        "Whenever you yawn summons 2 - 3 opened packets of any fast food condiment/sauce midair within a 15 meter radius.",
        "Every time bodily gases leave your body it makes the sound of a turbo",
        "When you smell a fart, you can tell exactly who that fart belongs to",
        "When you get angry you get superhuman strenght that allows you to surpass your limits by 1,5%",
        "Everytime you try to sleep, a horn blares in your ear",
        "you can eat metal but only osmium",
        "When you open a door someone will spawn behind you",
        "Every time you turn on the fan it turns off",
        "Every time you wear glasses you don't see clearly"
    ]
}


useful = {
    "Power": [
        "Whenever you need to remember something, you can instantly recall it with perfect clarity",
        "You can speak and understand every language in the world fluently",
        "You never have to sleep and always feel rested and energized",
        "You have the power of teleportation, allowing you to instantly travel anywhere in the world",
        "You have the ability to heal any injury or illness, including your own",
        "You have perfect control over your emotions and can always remain calm and focused",
        "You have superhuman strength and can lift any object with ease",
        "You can manipulate time, allowing you to slow it down or speed it up at will",
        "You have the power of flight and can soar through the sky like a bird",
        "You can read people's thoughts and emotions, giving you a deep understanding of their true intentions and feelings",
        "You can transform into any animal or creature, gaining their unique abilities and traits",
        "You have the ability to create and control fire, water, air, and earth",
        "You have the power of precognition, allowing you to see into the future and predict upcoming events",
        "You can instantly learn any skill or knowledge simply by observing it",
        "You have the ability to control and manipulate technology with your mind",
        "You can turn invisible at will, making you undetectable to others",
        "You have the power of telekinesis, allowing you to move objects with your mind",
        "You can enter any fictional universe or story and interact with its characters and events",
        "You have the ability to shapeshift your body into any form or appearance you desire",
        "You can understand and speak any language fluently, including sign language",
        "You have a perfect photographic memory and can remember anything you see or hear",
        "You can teleport to any location in the world instantly",
        "You have the power of telekinesis and can move objects with your mind",
        "You can create force fields around yourself or others for protection",
        "You have the ability to shapeshift into any animal or object",
        "You have the power of super speed and can move faster than the eye can see",
        "You can become invisible at will",
        "You have the ability to read people's thoughts",
        "You can control the elements (earth, water, air, fire) at will",
        "You have the power of flight and can soar through the skies",
        "You can heal any injury or illness instantly",
        "You have the power of telepathy and can communicate with others using only your mind",
        "You can summon any object or person to you instantly",
        "You have the ability to manipulate time and can travel to the past or future",
        "You have the power of precognition and can see into the future",
        "You can walk through walls and other solid objects",
        "You have the power of pyrokinesis and can control fire with your mind",
        "You can phase through solid objects, allowing you to move through walls and other barriers",
        "You have the ability to create illusions that can fool even the most perceptive individuals",
        "Time slows down by 50% whenever you're in danger",
        "Any object you touch can become weightless or as heavy as you desire",
        "Your dreams become lucid and you can control them at will",
        "You can communicate with animals and they understand you perfectly",
        "You have photographic memory and can remember anything you see or hear",
        "Your body automatically adjusts to any temperature, making you immune to extreme heat or cold",
        "You have the power of telekinesis and can move objects with your mind",
        "You are able to speak any language fluently, including those of aliens or mythical creatures",
        "You can teleport to any location you have previously visited or seen a picture of",
        "You have the ability to heal any injury or illness, including those of others",
        "You can shape shift into any animal or object at will",
        "You are immune to all poisons and toxins",
        "You can see perfectly in complete darkness",
        "You have the power of telepathy and can read other people's thoughts",
        "You can create force fields that protect you from any physical or energy-based attack",
        "You have the ability to control and manipulate fire, water, earth, and air",
        "You can travel through time and alter the course of history",
        "You have the power to fly at incredible speeds",
        "You can control and summon any type of weather",
        "Your bank account will always have exactly the amount of money you need to cover your expenses for the month",
        "You can understand and speak every language fluently, without the need for a translator",
        "You have a photographic memory, and can recall any information you've ever learned with perfect clarity",
        "Your physical appearance can change at will, allowing you to look however you want in any situation",
        "You always wake up feeling fully rested and energized, no matter how little sleep you got the night before",
        "You have perfect control over your emotions, and can choose exactly how you want to feel at any given moment",
        "You never get sick, and are immune to all diseases and illnesses",
        "You can teleport anywhere in the world instantly, without the need for any equipment or preparation",
        "You have the ability to stop time for everyone except yourself, allowing you to accomplish anything you want without any interruptions",
        "You always know the right thing to say or do in any situation, and can easily solve any problem that comes your way",
        "Time moves 50% slower for you, allowing you to get more done in less time",
        "Your memory is now eidetic, allowing you to recall every detail of any memory",
        "You now possess the power of telekinesis, enabling you to move objects with your mind",
        "You have the ability to instantly heal any injury or illness, making you virtually indestructible",
        "Your reflexes are now lightning fast, giving you an almost superhuman level of agility and reaction time",
        "You can now manipulate time itself, allowing you to travel through time or freeze time at will",
        "You possess the power of flight, enabling you to soar through the sky like a bird",
        "You are now able to speak and understand any language, making you a master communicator",
        "You now have perfect aim, allowing you to hit any target with precision and accuracy",
        "Your body now possesses superhuman strength and durability, making you virtually invincible",
        "You can now teleport to any location instantly, making travel a thing of the past",
        "You have the power to control the elements, manipulating fire, water, air, and earth to your will",
        "Your mind is now a supercomputer, capable of processing vast amounts of information at lightning speed",
        "You have the ability to shapeshift, transforming into any creature or object at will",
        "You possess the power of invisibility, allowing you to move undetected and unseen",
        "You can now breathe underwater, allowing you to explore the depths of the ocean with ease",
        "Your senses are now heightened, allowing you to see, hear, smell, taste, and feel with incredible clarity",
        "You possess the power of telepathy, enabling you to read minds and communicate with others without speaking",
        "You now have the power to create force fields, protecting yourself and others from harm",
        "You have the ability to generate and control electricity, giving you the power to shock your enemies or power entire cities"
        "Any damage taken is negated to the nearest rapist",
        "Any time you don't understand something time freezes and David Attenborough explains how the thing works",
        "Every time you drink water, it tastes like 3am water.",
        "Everytime you stub your toe a girl of your dream in a maid suit seduces you",
        "If you yell „Kobe“ before doing anything the success rate goes up by 84%",
        "Whenever you say „I wish I was better at ...“ you suddenly become 50% better at what you wished to become better at (stackable)",
        "Typing „Password“in to any account will let you in no matter who it is",
        "Every time you crack a finger you gain 5x power, speed, and intelligence for 10 minutes (stackable",
        "A siren blares in your head 1 minute before you're about to get caught doing something you shouldn't be doing",
        "Every time you say to yourself, „think think think.“ you automatically think the best possible solution for whatever situation you're in.",
        "A 5 minute sleep is an equivalent of 8 hours of sleep",
        "Once a week, you are allowed to make an announcement to the world that everyone hears telepathically.",
        "Any illness is diagnosed as just a Case of the Mondays. Next day, you're fine.",
        "Your chance of the person saying „yes“ when you ask them out increases by 50%",
        "If you dont like the way you look, you can go into a „customization mode“that lets you change anything and everything about your looks",
        "Anytime a girl touches you she is now 10% more attracted towards you",
        "Anytime a boy touches you he is now 10% more attracted towards you",
        "Any gun you touch has infinite ammo (video games included",
        "Whenever you feel like playing a video game, a PS5/Xbox, or high end pc will appear and load up that game no matter where you are",
        "If you are every attacked by anyone, Arthur Morgan will come out of nowhere and say „your ok boah“. from then on, you will gain a western revolver, and your punching strength will be upped by 37%.",
        "Every time you you see something you want/need but dont want to pay for it you can summon Elon Musk to buy it for you",
        "For each bacteria in your body, you get 1 dollar a month transferred to your bank acc at the last day of the month",
        "Whenever you feel like it you can enter your very own pocket dimension/universe",
        "Everytime you ask a girl out and they reject you become more handsome and smarter",
        "Whenever you stare at someone for more than 5 seconds, they get sent into a dimension where they can eat as many doritos locos tacos from taco bell as they want. (they get kicked out in 8 mins, but they can leave whenever",
        "Every time you rage in a game, you become 15% better at it",
        "If you say „ill try“whatever you do will have a 99% chance of working",
        "When someone says „who asked“, One person spawns out of nowhere and says „I did“ before disappearing!",
        "Everytime you see something and say „Dang, that's too expensive.“a random person buys it and gives it to you",
        "Each time someone compliments you a turtle will appear and give you a sandwich",
        "Any question you ask is answered fully and truthfully by Universe, even if it isn't known by anybody on Earth",
        "Everytime you say trickshot in a game you will 100% always hit it",
        "Every time someone says „who asked“a random midget will then come out of their own shoe and say „I asked“in a Db voice and vanish and leave behind a random number of shits in their shoe.",
        "Your pockets have infinite inventory space.",
        "Everytime you say you're hungry an old lady will appear and give you an all-you-can-eat buffet",
        "Everytime you do a good deed, 1 million dollars is added in your bank account",
        "All the food you eat is always at the optimal temperature you want it to be.",
        "Everytime you think of a bad/cringey memory, you earn 1000 dollars.",
        "Every firearm in your hand will have unlimited ammunition and will never jam",
        "Every time you go to sleep you will experience the best most vivid dream ever (including naps",
        "When you poop there will be no sound!"
    ]
}